name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次，按需调整时间
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出当前代码
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Step 2: 配置 git 用户信息
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # Step 3: 添加 upstream 并获取上游更新
    - name: Set up upstream
      run: |
        git remote add upstream https://github.com/guobao2333/DeepLX-Serverless.git
        git fetch upstream
        git checkout main
        git merge upstream/main --no-edit

    # Step 4: 推送更改到你的 fork 仓库
    - name: Push changes
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # 使用 GitHub Secrets
